import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const base=process.env.TEST_URL||'http://127.0.0.1:5173';
let passed=0;
function check(label,fn){fn();passed++;console.log('PASS '+label);}
function client(){let cookie='';return async(path,method='GET',data,headers={})=>{const r=await fetch(base+'/api/'+path,{method,headers:{'content-type':'application/json','x-questbound':'1',cookie,...headers},...(data?{body:JSON.stringify(data)}:{})});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return {status:r.status,body:await r.json(),cookie:set};};}
const a=client(),b=client(),anon=client();
const email='test-'+randomUUID()+'@example.com',password='A-test-passphrase-123';
check('unauthenticated state is rejected',()=>{});
assert.equal((await anon('state')).status,401);
let r=await a('auth','POST',{action:'signup',name:'QA Adventurer',email,password,timezone:'Asia/Kolkata'});
check('signup creates an HttpOnly session',()=>{assert.equal(r.status,200);assert.match(r.cookie,/HttpOnly/);});
r=await a('state');check('fresh account has no fabricated progress',()=>{assert.equal(r.body.xp,0);assert.equal(r.body.gold,0);assert.equal(r.body.tasks.length,0);});
await b('auth','POST',{action:'signup',name:'Other Adventurer',email:'other-'+randomUUID()+'@example.com',password,timezone:'UTC'});
r=await a('tasks','POST',{title:' ',category:'Intellect',difficulty:'easy'});check('blank tasks rejected',()=>assert.equal(r.status,400));
r=await a('tasks','POST',{title:'bad category',category:'Admin',difficulty:'easy'});check('unknown attribute rejected',()=>assert.equal(r.status,400));
r=await a('tasks','POST',{title:'bad date',category:'Intellect',difficulty:'easy',dueDate:'2026-02-30'});check('invalid calendar dates rejected',()=>assert.equal(r.status,400));
r=await a('tasks','POST',{title:'Write the first chapter',category:'Intellect',difficulty:'hard',xp:999999,gold:999999});
check('quest created',()=>assert.equal(r.status,201));const id=r.body.tasks[0].id;
r=await b('tasks','PATCH',{id,title:'stolen',category:'Craft',difficulty:'hard'});check('other account cannot edit quest',()=>assert.equal(r.status,409));
r=await b('complete','POST',{id});check('other account cannot complete quest',()=>assert.equal(r.status,404));
r=await b('tasks','DELETE',{id});check('other account cannot delete quest',()=>assert.equal(r.body.tasks.length,0));
r=await a('state');assert.equal(r.body.tasks.length,1);
r=await a('tasks','PATCH',{id,title:'Complete a focused work session',category:'Craft',difficulty:'hard'});check('quest editing persists',()=>assert.equal(r.body.tasks[0].title,'Complete a focused work session'));
const attempts=await Promise.all(Array.from({length:6},()=>a('complete','POST',{id,xp:999999,gold:999999})));
check('concurrent completion requests succeed safely',()=>attempts.forEach(x=>assert.equal(x.status,200)));
r=await a('state');check('server rewards awarded exactly once',()=>{assert.equal(r.body.xp,100);assert.equal(r.body.gold,40);assert.equal(r.body.history.length,1);assert.equal(r.body.attributes.Craft,100);});
check('nonlinear level and streak applied',()=>{assert.equal(r.body.progression.level,2);assert.equal(r.body.progression.required,400);assert.equal(r.body.streak,1);});
r=await a('tasks','PATCH',{id,title:'Change completed',category:'Strength',difficulty:'easy'});check('completed quest cannot be rewritten',()=>assert.equal(r.status,409));
r=await a('shop','POST',{itemId:'moonlit',price:0});check('insufficient balance cannot buy a theme',()=>assert.equal(r.status,409));
r=await a('shop','PATCH',{itemId:'moonlit'});check('unowned items cannot be equipped',()=>assert.equal(r.status,403));
await Promise.all(Array.from({length:6},()=>a('shop','POST',{itemId:'first-light',price:0})));
r=await a('state');check('parallel purchase debits once at server price',()=>{assert.equal(r.body.gold,10);assert.equal(r.body.inventory.length,1);});
r=await a('shop','PATCH',{itemId:'first-light'});check('owned badge can be equipped',()=>assert.equal(r.body.user.badge,'first-light'));
r=await a('tasks','DELETE',{id});check('archiving preserves immutable reward history',()=>{assert.equal(r.body.tasks.length,0);assert.equal(r.body.history.length,1);assert.equal(r.body.xp,100);});
r=await a('tasks','POST',{title:'cross-site',category:'Spirit',difficulty:'easy'},{origin:'https://evil.example'});check('cross-origin writes rejected',()=>assert.equal(r.status,403));
await a('auth','POST',{action:'logout'});r=await a('state');check('logout invalidates session',()=>assert.equal(r.status,401));
r=await a('auth','POST',{action:'login',email,password:'wrong-password-123'});check('wrong password rejected',()=>assert.equal(r.status,401));
r=await a('auth','POST',{action:'login',email,password});assert.equal(r.status,200);
r=await a('state');check('login restores persistent character and inventory',()=>{assert.equal(r.body.xp,100);assert.equal(r.body.gold,10);assert.equal(r.body.user.badge,'first-light');});
console.log(`\n${passed} checks passed against ${base}. Test accounts contain synthetic QA activity only.`);
