import { createRequire } from 'node:module';
import { mkdirSync, existsSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
const browser=await chromium.launch({headless:true,executablePath});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage(), errors=[];
page.on('pageerror',e=>errors.push(e.message));
mkdirSync('work/qa',{recursive:true});
await page.goto('http://127.0.0.1:5173');
await page.getByLabel('Adventurer name',{exact:true}).waitFor();
await page.screenshot({path:'work/qa/signup-desktop.png',fullPage:true,animations:'disabled'});
await page.getByLabel('Adventurer name',{exact:true}).fill('Gaurav');
await page.getByLabel('Email address',{exact:true}).fill('browser-'+Date.now()+'@example.com');
await page.getByLabel('Password',{exact:true}).fill('Demo-only-password-123');
await page.getByRole('button',{name:'Begin my adventure',exact:true}).click();
await page.getByRole('button',{name:'New quest',exact:true}).waitFor();
async function quest(title,attribute,effort){await page.getByRole('button',{name:'New quest',exact:true}).click();await page.getByLabel('What will you do?',{exact:true}).fill(title);await page.getByLabel('Attribute',{exact:true}).selectOption(attribute);await page.getByRole('radio',{name:new RegExp(effort)}).check();await page.getByRole('button',{name:'Add to my journal',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});}
await quest('Read a chapter of Atomic Habits','Intellect','Steady effort');
await quest('Go for a 20-minute walk','Strength','Small step');
await quest('Build something I am proud of','Craft','Brave challenge');
await quest('Write down three things I am grateful for','Spirit','Small step');
await page.screenshot({path:'work/qa/journal-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Edit Read a chapter of Atomic Habits',exact:true}).click();
await page.getByLabel('What will you do?',{exact:true}).fill('Read 20 pages of Atomic Habits');
await page.getByRole('button',{name:'Save changes',exact:true}).click();
await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByRole('button',{name:'Complete Build something I am proud of',exact:true}).click();
await page.getByRole('heading',{name:'Level 2',exact:true}).waitFor();
await page.screenshot({path:'work/qa/level-up.png'});
await page.getByRole('button',{name:'On to the next chapter',exact:true}).click();
await page.getByRole('button',{name:'The marketplace',exact:true}).click();
await page.getByRole('button',{name:'Unlock reward',exact:true}).click();
await page.getByRole('button',{name:'Equip reward',exact:true}).click();
await page.getByRole('button',{name:'Equipped',exact:true}).waitFor();
await page.getByRole('button',{name:'My character',exact:true}).click();
await page.getByText('First Light',{exact:true}).waitFor();
await page.reload();
await page.getByRole('button',{name:'My character',exact:true}).click();
await page.getByText('First Light',{exact:true}).waitFor();
await page.screenshot({path:'work/qa/character-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Adventure log',exact:true}).click();
await page.getByRole('heading',{name:'Build something I am proud of',exact:true}).waitFor();
await page.getByRole('button',{name:/Quest journal/}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'work/qa/journal-mobile.png',fullPage:true,animations:'disabled'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile horizontal overflow');
await page.getByRole('button',{name:'Toggle navigation',exact:true}).click();
await page.getByRole('button',{name:'The marketplace',exact:true}).click();
await page.screenshot({path:'work/qa/marketplace-mobile.png',fullPage:true,animations:'disabled'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'shop mobile horizontal overflow');
await page.setViewportSize({width:1440,height:1000});
await page.getByRole('button',{name:/Quest journal/}).click();
await context.setOffline(true);
await page.getByRole('button',{name:'New quest',exact:true}).click();
await page.getByLabel('What will you do?',{exact:true}).fill('Offline input is preserved');
await page.getByRole('button',{name:'Add to my journal',exact:true}).click();
await page.getByRole('alert').waitFor();
assert.equal(await page.getByLabel('What will you do?',{exact:true}).inputValue(),'Offline input is preserved');
await context.setOffline(false);
await page.getByRole('button',{name:'Add to my journal',exact:true}).click();
await page.getByRole('dialog').waitFor({state:'hidden'});
assert.deepEqual(errors,[],'no unhandled runtime errors');
writeFileSync('work/qa/browser-results.json',JSON.stringify({passed:true,checks:['signup','create','edit','complete','level up','buy and equip','refresh persistence','history','mobile journal','mobile shop','offline input preserved and retry'],runtimeErrors:errors},null,2));
console.log('PASS browser workflows, mobile widths, offline recovery, and no runtime errors');
await browser.close();


