'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Coins, Compass, Crown, Flame, Heart, Leaf, LogOut, Menu, Moon, Mountain, Pencil, Plus, Shield, ShoppingBag, Sparkles, Sun, Sword, Trash2, Trophy, WandSparkles, X, Zap, History, RefreshCw } from 'lucide-react';
import { categories, difficulties, progression } from '../lib/game';

type Quest = {id:string;title:string;category:string;difficulty:keyof typeof difficulties;due_date:string|null;completed_at:string|null};
type Game = {user:{id:string;name:string;email:string;timezone:string;theme:string;badge:string|null}; tasks:Quest[];history:any[];inventory:any[];shop:any[];xp:number;gold:number;progression:ReturnType<typeof progression>;streak:number;today:string;attributes:Record<string,number>};
const attrIcons:any={Intellect:BookOpen,Strength:Sword,Spirit:Heart,Craft:WandSparkles};
const itemIcons:any={sun:Sun,leaf:Leaf,moon:Moon,compass:Compass};
const emptyDraft={title:'',category:'Intellect',difficulty:'medium',dueDate:''};
const titles=['Wanderer','Pathfinder','Trailkeeper','Wayfarer','Guardian','Luminary'];
async function api(path:string,method='GET',data?:any) {
 let r:Response;
 try { r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-Questbound':'1'},...(data?{body:JSON.stringify(data)}:{})}); } catch { throw new Error('You seem to be offline. Your changes have not been saved. Reconnect and try again.'); }
 let value:any; try { value=await r.json(); } catch { throw new Error('Your journal is temporarily unavailable. Try again shortly.'); }
 if(!r.ok) { const e:any=new Error(value.error||'Something went wrong. Please try again.'); e.status=r.status; throw e; } return value;
}
function Icon({category,...props}:any){const I=attrIcons[category]||Sparkles;return <I {...props}/>;}
function Modal({open,onClose,title,children}:any){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();else if(!open&&ref.current?.open)ref.current?.close();},[open]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title} className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;}
export default function Questbound(){
 const [game,setGame]=useState<Game|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
 const [view,setView]=useState('quests'),[filter,setFilter]=useState('Active'),[category,setCategory]=useState('All');
 const [authMode,setAuthMode]=useState('signup'),[authError,setAuthError]=useState(''),[busy,setBusy]=useState('');
 const [notice,setNotice]=useState(''),[editor,setEditor]=useState(false),[draft,setDraft]=useState<any>(emptyDraft),[formError,setFormError]=useState('');
 const [remove,setRemove]=useState<Quest|null>(null),[levelUp,setLevelUp]=useState<number|null>(null),[mobileNav,setMobileNav]=useState(false),[about,setAbout]=useState(false);
 const notificationTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function notify(s:string){setNotice(s);if(notificationTimer.current)clearTimeout(notificationTimer.current);notificationTimer.current=setTimeout(()=>setNotice(''),6000);}
 async function load(){setLoadError('');try{setGame(await api('state'));}catch(e:any){if(e.status!==401)setLoadError(e.message);else setGame(null);}finally{setLoading(false);}}
 useEffect(()=>{load();return()=>{if(notificationTimer.current)clearTimeout(notificationTimer.current);};},[]);
 useEffect(()=>{function onFocus(){if(game)load();}window.addEventListener('focus',onFocus);return()=>window.removeEventListener('focus',onFocus);},[game?.user.id]);
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setAuthError('');setBusy('auth');const f=new FormData(e.currentTarget);try{await api('auth','POST',{action:authMode,email:f.get('email'),password:f.get('password'),name:f.get('name'),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});await load();}catch(e:any){setAuthError(e.message);}finally{setBusy('');}}
 async function mutate(path:string,method:string,data:any,key:string,message:string){setBusy(key);try{const next=await api(path,method,data);if(game&&next.progression.level>game.progression.level)setLevelUp(next.progression.level);setGame(next);notify(message);return true;}catch(e:any){notify(e.message);if(e.status===401)setGame(null);return false;}finally{setBusy('');}}
 function openEditor(q?:Quest){setDraft(q?{id:q.id,title:q.title,category:q.category,difficulty:q.difficulty,dueDate:q.due_date||''}:{...emptyDraft});setFormError('');setEditor(true);}
 async function saveQuest(e:React.FormEvent){e.preventDefault();setFormError('');setBusy('save');try{setGame(await api('tasks',draft.id?'PATCH':'POST',draft));setEditor(false);notify(draft.id?'Quest updated. Your path is yours to shape.':'A new quest awaits. You’ve got this.');}catch(e:any){setFormError(e.message);}finally{setBusy('');}}
 const completedToday=game?.history.filter(q=>q.day===game.today).length||0;
 const active=game?.tasks.filter(q=>!q.completed_at)||[];
 const list=game?.tasks.filter(q=>(filter==='Active'?!q.completed_at:!!q.completed_at)&&(category==='All'||q.category===category))||[];
 const equippedBadge=game?.shop.find(i=>i.id===game.user.badge);
 return <div className={`app ${game?.user.theme==='moonlit'?'night':''}`}>
 <a className="skip" href="#main">Skip to main content</a>
 {loading?<main className="loading-screen" id="main"><Compass className="loading-compass" size={42}/><h1>Opening your journal…</h1><p>Your next chapter is waiting.</p></main>:!game?
 <main className="auth-shell" id="main">
  <section className="auth-art"><img src="/realm.webp" alt="An orange-cloaked traveler overlooking a floating sanctuary and misty forests"/><div className="auth-overlay"/><a href="/" className="brand"><Compass size={30}/><span>questbound<span className="brand-dot">.</span></span></a><div className="auth-story"><span className="eyebrow light">A LITTLE PROGRESS. A GRAND ADVENTURE.</span><h1>Your life.<br/>Your next <em>chapter.</em></h1><p>Turn everyday intentions into quests.<br/>Grow a little stronger, one small win at a time.</p><div className="story-chips"><span><Sword size={16}/> Real-life quests</span><span><Sparkles size={16}/> Meaningful growth</span></div></div><span className="art-credit">THE EMERALD EXPANSE · YOUR JOURNEY BEGINS HERE</span></section>
  <section className="auth-panel"><div className="auth-top"><span>Life, with a little more magic.</span><button className="text-button" onClick={()=>setAbout(true)}>By TechTitan <ChevronRight size={15}/></button></div><div className="auth-form-wrap"><span className="round-icon"><Compass size={30}/></span><span className="eyebrow">WELCOME, ADVENTURER</span><h2>{authMode==='signup'?'Every hero starts somewhere.':'Your adventure continues.'}</h2><p className="muted">{authMode==='signup'?'Create your character. Make the ordinary extraordinary.':'Open your journal and pick up where you left off.'}</p>
  <div className="auth-tabs" aria-label="Account action"><button aria-pressed={authMode==='signup'} className={authMode==='signup'?'selected':''} onClick={()=>{setAuthMode('signup');setAuthError('');}}>Create account</button><button aria-pressed={authMode==='login'} className={authMode==='login'?'selected':''} onClick={()=>{setAuthMode('login');setAuthError('');}}>Sign in</button></div>
  <form onSubmit={auth}>{authMode==='signup'&&<label>Adventurer name<input name="name" autoComplete="nickname" placeholder="What should we call you?" maxLength={40} required/></label>}<label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" maxLength={254} required/></label><label>Password<input name="password" type="password" autoComplete={authMode==='signup'?'new-password':'current-password'} placeholder="At least 10 characters" minLength={10} maxLength={128} required/></label>
  {(authError||loadError)&&<p className="error" role="alert">{authError||loadError}</p>}
  <button className="primary full" disabled={!!busy}>{busy==='auth'?'Opening the gates…':authMode==='signup'?'Begin my adventure':'Return to my adventure'}<ArrowRight size={18}/></button></form>
  <p className="auth-note"><Shield size={15}/> Your own quests. Your own pace. Progress saved across devices.</p></div><footer className="auth-footer"><span>QUESTBOUND · LIFE RPG</span><span>Made with purpose by TechTitan</span></footer></section>
 </main>:
 <div className="workspace">
  <aside className={`sidebar ${mobileNav?'mobile-open':''}`}><a href="/" className="brand"><Compass size={27}/><span>questbound<span className="brand-dot">.</span></span></a><span className="sidebar-caption">MAKE EVERY DAY AN ADVENTURE</span>
  <div className="chapter-label">YOUR JOURNEY</div><nav aria-label="Main navigation">{[{id:'quests',label:'Quest journal',icon:BookOpen},{id:'character',label:'My character',icon:Shield},{id:'shop',label:'The marketplace',icon:ShoppingBag},{id:'history',label:'Adventure log',icon:History}].map(n=><button key={n.id} className={view===n.id?'nav-item active':'nav-item'} aria-current={view===n.id?'page':undefined} onClick={()=>{setView(n.id);setMobileNav(false);}}><n.icon size={20}/><span>{n.label}</span>{n.id==='quests'&&<span className="nav-count">{active.length}</span>}</button>)}</nav>
  <div className="sidebar-note"><Leaf size={23}/><p>Great things grow<br/>from small beginnings.</p><span>One quest at a time.</span></div>
  <div className="sidebar-bottom"><button className="nav-item" onClick={()=>setAbout(true)}><Compass size={19}/> The makers’ guild</button><div className="profile-mini"><div className="avatar">{game.user.name.slice(0,1).toUpperCase()}</div><div><strong>{game.user.name}</strong><span>Level {game.progression.level} {titles[Math.min(game.progression.level-1,5)]}</span></div><button className="icon-button" aria-label="Sign out" disabled={!!busy} onClick={async()=>{setBusy('logout');try{await api('auth','POST',{action:'logout'});setGame(null);setAuthMode('login');setView('quests');}catch(e:any){notify(e.message);}finally{setBusy('');}}}><LogOut size={18}/></button></div></div></aside>
  {mobileNav&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setMobileNav(false)}/>}
  <div className="main-column"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle navigation" aria-expanded={mobileNav}><Menu/></button><span>Your adventure</span><ChevronRight size={14}/><strong>{{quests:'Quest journal',character:'My character',shop:'The marketplace',history:'Adventure log'}[view]}</strong></div><div className="topbar-stats"><span className="streak-pill"><Flame size={17}/><strong>{game.streak}</strong><span>day streak</span></span><span className="gold-pill"><Coins size={18}/><strong>{game.gold}</strong><span>gold</span></span></div></header>
  <main id="main" className="main-content"><div className="page-heading"><div><span className="eyebrow">{new Date(game.today+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</span><h1>{view==='quests'?<>Make today a good chapter<span className="heading-dot">.</span></>:view==='character'?'Meet your growing self.':view==='shop'?'A little reward for your effort.':'Look how far you’ve come.'}</h1><p>{view==='quests'?`Welcome back, ${game.user.name.split(' ')[0]}. Every small step counts.`:view==='character'?'Every quest leaves a little magic behind.':view==='shop'?'Earn gold through real-life quests. Spend it on a little magic.':'Your completed quests, safely kept in your journal.'}</p></div>{view==='quests'&&<button className="primary" onClick={()=>openEditor()}><Plus size={19}/> New quest</button>}</div>
  {loadError&&<div className="error" role="alert">{loadError}<button className="text-button" onClick={load}><RefreshCw size={15}/> Retry</button></div>}
  {view==='quests'&&<><section className="realm-banner"><img src="/realm.webp" alt="A traveler exploring the Emerald Expanse"/><div className="realm-shade"/><div className="realm-copy"><span className="realm-tag"><Compass size={13}/> CHAPTER {String(game.progression.level).padStart(2,'0')} · THE EMERALD EXPANSE</span><h2>{game.progression.level===1?'The journey begins with you.':'A little further. A little stronger.'}</h2><p>There’s a whole world in who you could become.</p><div className="banner-progress"><span>Level {game.progression.level} <b>{titles[Math.min(game.progression.level-1,5)]}</b></span><span>{game.progression.current} / {game.progression.required} XP</span></div><div className="progress-track"><span style={{width:game.progression.percent+'%'}}/></div></div><span className="banner-location">01 / THE EMERALD EXPANSE</span></section>
  <div className="stats-row"><div className="stat-card"><span className="stat-icon green"><Check/></span><div><span>Quests conquered today</span><strong>{completedToday}<small>small wins, real growth</small></strong></div></div><div className="stat-card"><span className="stat-icon amber"><Flame/></span><div><span>Your current streak</span><strong>{game.streak} <small>{game.streak===1?'day of showing up':'days of showing up'}</small></strong></div></div><div className="stat-card"><span className="stat-icon lilac"><Sparkles/></span><div><span>Experience earned</span><strong>{game.xp}<small>XP on your journey</small></strong></div></div></div>
  <div className="journal-layout"><section className="quest-section"><div className="section-title"><h2>Your quests <span>{active.length} to go</span></h2><select value={category} aria-label="Filter by attribute" onChange={e=>setCategory(e.target.value)}><option value="All">All attributes</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="tabs">{['Active','Completed'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'selected':''} aria-pressed={filter===f}>{f}<span>{f==='Active'?active.length:game.tasks.length-active.length}</span></button>)}</div>
  <div className="quest-list">{list.map(q=><article className={`quest ${q.completed_at?'done':''}`} key={q.id}><button className={`complete-button ${q.completed_at?'checked':''}`} aria-label={q.completed_at?`${q.title} completed`:`Complete ${q.title}`} disabled={!!q.completed_at||!!busy} onClick={()=>mutate('complete','POST',{id:q.id},q.id,`Quest complete! +${difficulties[q.difficulty].xp} XP and +${difficulties[q.difficulty].gold} gold.`)}>{busy===q.id?<span className="spinner"/>:q.completed_at?<Check size={16}/>:null}</button><div className="quest-details"><h3>{q.title}</h3><div className="quest-meta"><span className={'attribute-tag '+q.category.toLowerCase()}><Icon category={q.category} size={12}/>{q.category}</span><span>{difficulties[q.difficulty].label}</span>{q.due_date&&<span className={!q.completed_at&&q.due_date<game.today?'overdue':''}>{q.due_date===game.today?'Today':q.due_date}</span>}</div></div><div className="quest-reward"><span>+{difficulties[q.difficulty].xp} XP</span><small><Coins size={12}/>{difficulties[q.difficulty].gold}</small></div><div className="quest-actions">{!q.completed_at&&<button className="icon-button" onClick={()=>openEditor(q)} aria-label={`Edit ${q.title}`}><Pencil size={15}/></button>}<button className="icon-button" onClick={()=>setRemove(q)} aria-label={`${q.completed_at?'Archive':'Delete'} ${q.title}`}><Trash2 size={15}/></button></div></article>)}</div>
  {!list.length&&<div className="empty-state"><BookOpen size={32}/><h3>{filter==='Completed'?'Your victories will live here.':category!=='All'?'A fresh page for this attribute.':'A blank page. Endless possibilities.'}</h3><p>{filter==='Completed'?'Complete a quest to record your first win.':'Start with one small thing you want to do today.'}</p>{filter==='Active'&&<button className="text-button" onClick={()=>openEditor()}><Plus size={16}/> Write your first quest</button>}</div>}
  <button className="add-quest-row" onClick={()=>openEditor()}><Plus size={17}/> A small step worth taking…</button>
  {!game.tasks.length&&<div className="starter-quests"><span>NEED A LITTLE INSPIRATION?</span>{[{title:'Read 10 pages',category:'Intellect'},{title:'Move for 20 minutes',category:'Strength'},{title:'Take a quiet moment',category:'Spirit'}].map(q=><button key={q.title} onClick={()=>{setDraft({...emptyDraft,...q,difficulty:'easy'});setFormError('');setEditor(true);}}>{q.title}<Plus size={13}/></button>)}</div>}</section>
  <aside className="growth-card"><span className="eyebrow">A LITTLE STRONGER, EVERY DAY</span><h2>Your attributes</h2><p>Different quests. A more balanced you.</p>{categories.map(c=><div className="attribute-row" key={c}><div><span className={'attribute-symbol '+c.toLowerCase()}><Icon category={c} size={17}/></span><strong>{c}</strong><span>Lv. {Math.floor(game.attributes[c]/100)+1}</span></div><div className={'attribute-track '+c.toLowerCase()}><span style={{width:(game.attributes[c]%100)+'%'}}/></div><small>{game.attributes[c]} XP earned</small></div>)}<button className="text-button full" onClick={()=>setView('character')}>View my character<ArrowRight size={16}/></button></aside></div></>}
  {view==='character'&&<div className="character-layout"><section className="character-card"><div className="character-art"><img src="/realm.webp" alt="Your adventure through the Emerald Expanse"/><span className="character-avatar">{game.user.name.slice(0,1).toUpperCase()}</span></div><span className="eyebrow">LEVEL {game.progression.level} · {titles[Math.min(game.progression.level-1,5)].toUpperCase()}</span><h2>{game.user.name}</h2>{equippedBadge&&<span className="equipped-badge"><Crown size={16}/>{equippedBadge.name}</span>}<p>{game.progression.required-game.progression.current} XP until your next level</p><div className="progress-track"><span style={{width:game.progression.percent+'%'}}/></div><div className="character-totals"><span><strong>{game.history.length}</strong>quests completed</span><span><strong>{game.xp}</strong>total XP</span><span><strong>{game.streak}</strong>day streak</span></div></section><section className="character-attributes"><h2>The many sides of you</h2><p className="muted">Your stats grow from the quests you actually complete.</p>{categories.map(c=><div className="large-attribute" key={c}><span className={'stat-icon '+c.toLowerCase()}><Icon category={c}/></span><div><h3>{c}<span>Level {Math.floor(game.attributes[c]/100)+1}</span></h3><p>{{Intellect:'Learning, reading, and focused thinking.',Strength:'Movement, exercise, and physical wellbeing.',Spirit:'Rest, connection, and a clearer mind.',Craft:'Building, creating, and practicing your skills.'}[c]}</p><div className={'attribute-track '+c.toLowerCase()}><span style={{width:(game.attributes[c]%100)+'%'}}/></div><small>{game.attributes[c]%100} / 100 XP to the next attribute level</small></div></div>)}<div className="rules-note"><Sparkles size={19}/><p>Character levels take more effort as you grow: 100 XP, then 400 XP, then 900 XP. Each attribute levels up every 100 XP.</p></div></section></div>}
  {view==='shop'&&<><div className="shop-intro"><div><Coins size={30}/><div><span>YOUR GOLD POUCH</span><strong>{game.gold} <small>gold to spend</small></strong></div></div><p>Little treasures, earned one quest at a time.</p></div><div className="shop-grid">{game.shop.map(item=>{const I=itemIcons[item.icon],owned=game.inventory.some(i=>i.item_id===item.id),equipped=game.user.theme===item.id||game.user.badge===item.id;return <article className={'shop-card '+item.icon} key={item.id}><div className="item-art"><I size={64} strokeWidth={1.2}/><span>{item.kind==='theme'?'REALM THEME':'CHARACTER BADGE'}</span></div><div className="shop-card-body"><h2>{item.name}</h2><p>{item.description}</p><div className="shop-price"><Coins size={17}/>{item.price}<span>gold</span></div><button className={owned?'secondary full':'primary full'} disabled={!!busy||equipped||(!owned&&game.gold<item.price)} onClick={()=>mutate('shop',owned?'PATCH':'POST',{itemId:item.id},item.id,owned?`${item.name} equipped.`:`${item.name} unlocked! Equip it to make it yours.`)}>{busy===item.id?'Opening your treasure…':equipped?'Equipped':owned?'Equip reward':game.gold<item.price?`${item.price-game.gold} more gold to unlock`:'Unlock reward'}{owned&&<Check size={16}/>}</button></div></article>;})}</div>{game.user.theme==='moonlit'&&<button className="secondary" disabled={!!busy} onClick={()=>mutate('shop','PATCH',{itemId:'daylight'},'theme','Daylight has returned to your journal.')}><Sun size={16}/> Return to daylight</button>}</>}
  {view==='history'&&<section className="history-panel"><div className="section-title"><h2>Your story so far</h2><span>{game.history.length} quests conquered</span></div>{!game.history.length?<div className="empty-state"><History size={34}/><h3>The best stories start with a first step.</h3><p>Complete your first quest and it will appear here.</p><button className="primary" onClick={()=>setView('quests')}>Open quest journal <ArrowRight size={16}/></button></div>:game.history.map(h=><article className="history-row" key={h.id}><span className={'stat-icon '+h.category.toLowerCase()}><Icon category={h.category} size={20}/></span><div><h3>{h.title}</h3><p>{h.category} · {new Date(h.created_at).toLocaleString('en-US',{timeZone:game.user.timezone,dateStyle:'medium',timeStyle:'short'})}</p></div><div><strong>+{h.xp} XP</strong><span><Coins size={14}/> +{h.gold} gold</span></div></article>)}<p className="history-note"><Shield size={15}/> Completed quests stay in your history, even after you archive them. Times shown in {game.user.timezone}.</p></section>}
  <footer className="workspace-footer"><span><Leaf size={14}/> Progress, at your own pace.</span><button className="text-button" onClick={()=>setAbout(true)}>Questbound by TechTitan</button></footer>
  </main></div></div>}
 <Modal open={editor} onClose={()=>{if(busy!=='save')setEditor(false);}} title={draft.id?'Shape your quest':'A new quest awaits'}><p className="muted">Make it specific. Make it achievable. Make it yours.</p><form onSubmit={saveQuest}><label>What will you do?<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} maxLength={160} required placeholder="e.g. Finish one chapter of my book"/></label><div className="form-row"><label>Attribute<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Due date <small>(optional)</small><input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label></div><fieldset><legend>How big is this step?</legend><div className="difficulty-options">{Object.entries(difficulties).map(([key,d])=><label key={key} className={draft.difficulty===key?'chosen':''}><input type="radio" name="difficulty" value={key} checked={draft.difficulty===key} onChange={()=>setDraft({...draft,difficulty:key})}/><span>{d.label}</span><strong>{d.xp} XP</strong><small>{d.gold} gold</small></label>)}</div></fieldset><p className="form-help">Choose the effort honestly. Rewards are granted once, when you complete the quest.</p>{formError&&<p role="alert" className="error">{formError}</p>}<button className="primary full" disabled={!!busy}>{busy==='save'?'Saving your quest…':draft.id?'Save changes':'Add to my journal'}<Plus size={17}/></button></form></Modal>
 <Modal open={!!remove} onClose={()=>setRemove(null)} title={remove?.completed_at?'Archive this quest?':'Let this quest go?'}><p>“{remove?.title}”</p><p className="muted">{remove?.completed_at?'Your XP, gold, and adventure log will stay with you.':'It’s okay to change your plans. This will remove the quest from your journal.'}</p><div className="dialog-actions"><button className="secondary" onClick={()=>setRemove(null)}>Keep quest</button><button className="danger" disabled={!!busy} onClick={async()=>{if(await mutate('tasks','DELETE',{id:remove?.id},'delete','Your journal has been updated.'))setRemove(null);}}>{busy==='delete'?'Updating…':remove?.completed_at?'Archive quest':'Delete quest'}</button></div></Modal>
 <Modal open={!!levelUp} onClose={()=>setLevelUp(null)} title="A new chapter begins"><div className="level-celebration"><div className="level-rays"><Trophy size={64}/></div><span className="eyebrow">LOOK AT YOU GROW</span><h2>Level {levelUp}</h2><p>You are now a <strong>{titles[Math.min((levelUp||1)-1,5)]}</strong>.<br/>Your real-world effort is becoming something extraordinary.</p><button className="primary full" onClick={()=>setLevelUp(null)}>On to the next chapter <ArrowRight size={18}/></button></div></Modal>
 <Modal open={about} onClose={()=>setAbout(false)} title="The makers’ guild"><div className="makers"><Compass size={38}/><span className="eyebrow">QUESTBOUND · LIFE RPG</span><h3>Built by TechTitan</h3><p>A daily quest journal that makes small, real-world actions feel worth celebrating.</p><ul><li><strong>Gaurav Vyas</strong><span>Team leader</span></li><li><strong>Utkarsh Umang</strong><span>Team member</span></li><li><strong>Shivam Salve</strong><span>Team member</span></li></ul><p className="muted">Tech Zephyr 4.0 · Web Hackathon<br/>IIT Bhubaneswar</p></div></Modal>
 <div className={`toast ${notice?'visible':''}`} role="status" aria-live="polite"><Sparkles size={20}/><span>{notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>
 </div>;
}
